.Dd $Mdocdate: 1 June 2020 $
.Dt svnlayered-fuse 1
.Os
.Sh NAME
.Nm svnlayered-fuse
.Nd file system in userland
.Sh SYNOPSIS
.Cd "svnlayered-fuse -l /under -l /work /mnt"
.Sh DESCRIPTION
Use fuse to mount a similar system to overlayfs with a bit more inside
.Sh SEE ALSO
.Xr fuse 4 ,
.Sh HISTORY
Is written by the winner
